version: "3"
services:
  node-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=swvl
      - MONGO_INITDB_ROOT_PASSWORD=swvl
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
